version: '3.9'
services:
  api:
    container_name: task-manager-server
    depends_on:
      - db
    build: .
    ports:
      - 4000:4000
    environment:
      - DATABASE_URL=${DATABASE_URL}
  db:
    container_name: postgres
    image: postgres:14-alpine
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
