version: '3.9'
services:
  api:
    depends_on:
      - db
      - cache
    command: npm run test
  db:
    container_name: postgres
    image: postgres:14-alpine
    restart: always
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  cache:
    container_name: redis
    image: redis:7.0
    restart: always
    ports:
      - ${REDIS_PORT}:6379
    command: redis-server --save 60 1 --loglevel warning
