version: '3.9'
services:
  api:
    container_name: task-manager-server
    image: reenanfs/task-manager-server
    build:
      context: .
      target: ${DOCKER_TARGET}
    ports:
      - 4000:4000
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NODE_ENV=${NODE_ENV}
