version: '3.9'
services:
  api:
    depends_on:
      - db
      - cache
    volumes:
      - /app/node_modules
      - ./:/app
  db:
    container_name: postgres
    image: postgres:14-alpine
    restart: always
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
  cache:
    container_name: redis
    image: redis:7.0
    ports:
      - ${REDIS_PORT}:6379
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis-data:/data
volumes:
  pgdata:
  redis-data:
