name: server-tests
on: 
  - push
  - pull_request
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm i
      - name: Run unit tests
        run: npm run test
      - name: Run e2e tests
        run: npm run test:e2e
